### ISSUE TITLE
cddl tool group choice error

### ISSUE THREAD

**Issue by ii8** [cbor-wg/cddl#5]
The below cddl spec will throw an error when run with the cddl tool. Maybe I am using the language wrong but I cannot work out from the error message where my mistake lies.

What confuses me is that if b is an anonymous group this works fine.
```
a = {
  b
}

b = (
  (x: int // y: int), z: int
)
```

The command and its output:
```
λ cddl test.cddl generate
/Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1031:in `grpent': [[:grpchoice, [[:member, 1, 1, [:text, "x"], [:type1, [:prim, 0], [:prim, 1]]]], [[:member, 1, 1, [:text, "y"], [:type1, [:prim, 0], [:prim, 1]]]]], [:member, 1, 1, [:text, "z"], [:type1, [:prim, 0], [:prim, 1]]]] (RuntimeError)
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1239:in `block (2 levels) in group'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1239:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1239:in `flat_map'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1239:in `block in group'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1238:in `map'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1238:in `group'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1189:in `block in type1'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1189:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1189:in `flat_map'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:1189:in `type1'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:933:in `block in r_process'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:922:in `map'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:922:in `r_process'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:225:in `rules'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/lib/cddl.rb:254:in `generate'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/bin/cddl:68:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/bin/cddl:67:in `times'
        from /Library/Ruby/Gems/2.3.0/gems/cddl-0.8.5/bin/cddl:67:in `<top (required)>'
        from /usr/local/bin/cddl:22:in `load'
        from /usr/local/bin/cddl:22:in `<main>'
```

**Comment by cabo** [comment]
Hi Murray,  this is indeed a limitation of the current tool. I'm in the middle of fixing a related bug and may be able to lift that limitation in the same process...  For now, not having the group choice as the first element of the group should help.

**Comment by cabo** [comment]
Or not, oops.  Yes, I'll have to look at this some more.

**Comment by matt-cross** [comment]
I ran into this while trying to understand the language as well.  I don't have a real-world use case, but I am trying to understand what the intended interpretation in the language would be of something like this:

```
toplevel = {group1}

group2 = (
       *tstr => uint //
       red : 3
)

group1 = (
       group2,
       red : 1,
       black : 2,
)
```

Is the occurence specifier on the first item in group2 greedy or minimal?  IE will it match only until it sees something that matches something later on (such as `red:3` or `red:1`), or will it match all `tstr:uint`'s and then fail to match the required later elements in group1?

**Comment by matt-cross** [comment]
I see now that the specification in your other repo at https://github.com/cbor-wg/cddl has more details than the latest version on IETF's site (https://tools.ietf.org/html/draft-greevenbosch-appsawg-cbor-cddl-11) which seems to answer my question.  If I understand correctly, it will be greedy and is not recommended.
